// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABD5dtdSqxkADNBNsYceqt6MDkiu0PGIU',
    appId: '1:885688802427:web:b2e3764e37bb78036a16de',
    messagingSenderId: '885688802427',
    projectId: 'babble-41',
    authDomain: 'babble-41.firebaseapp.com',
    storageBucket: 'babble-41.appspot.com',
    measurementId: 'G-7CDRKEZYK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGEVYBFG3Y-lOSU3GjYlUdiuSDHZ64YHw',
    appId: '1:885688802427:android:ea1e1ef6dbb6ef076a16de',
    messagingSenderId: '885688802427',
    projectId: 'babble-41',
    storageBucket: 'babble-41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZm-VkOqXJECWfo3QbSDud977xedTX4Kc',
    appId: '1:885688802427:ios:3d6e9e9cd11e59236a16de',
    messagingSenderId: '885688802427',
    projectId: 'babble-41',
    storageBucket: 'babble-41.appspot.com',
    iosBundleId: 'com.example.babble',
  );
}
